"""
Regression test for #43: node coordinates in the root tile were shifted by
180 degrees when two consecutive nodes of the root pile were more than half
a world apart, because the 64-bit varint coordinate deltas written by the
sorter were read back through a 32-bit accumulator.

The fixture (test/data/halfworld.osm.pbf, generated by
test/data/make_halfworld.py) holds two 3-node ways 200 degrees apart. Built
into a single-tile GOL, the second way used to come out at lon -80 instead
of lon 100.

Point GOL_EXE at the binary under test, e.g.
    GOL_EXE=build/gol python3 -m pytest test/test_root_tile.py
"""
import json
import re
import sys
from pathlib import Path

import pytest

from conftest import run

DATA_DIR = Path(__file__).parent / "data"
FIXTURE = DATA_DIR / "halfworld.osm.pbf"

sys.path.insert(0, str(DATA_DIR))
from make_halfworld import NODES, WAYS  # noqa: E402  (single source of truth)


def tile_count(gol_path):
    res = run(["info", str(gol_path)])
    assert res.returncode == 0, res.stderr
    match = re.search(r"Tiles:\s*([\d,]+)", res.stdout)
    assert match, res.stdout
    return int(match.group(1).replace(",", ""))


def way_coordinates(gol_path):
    """way id -> [(lon, lat), ...] as reported by `gol query w -f geojson`."""
    res = run(["query", str(gol_path), "w", "-f", "geojson"])
    assert res.returncode == 0, res.stderr
    coords = {}
    for feature in json.loads(res.stdout)["features"]:
        assert feature["id"].startswith("W")
        assert feature["geometry"]["type"] == "LineString"
        coords[int(feature["id"][1:])] = [
            (lon, lat) for lon, lat in feature["geometry"]["coordinates"]
        ]
    return coords


# "-l 0" pins the pyramid to the root tile; the default settings also give a
# single tile for such a tiny input, but that depends on --min-tile-density.
@pytest.mark.parametrize("build_options", [["-l", "0"], []])
def test_root_tile_keeps_far_apart_nodes(tmp_path, build_options):
    gol_path = tmp_path / "halfworld.gol"
    res = run(["build", str(gol_path), str(FIXTURE), "-Y"] + build_options)
    assert res.returncode == 0, res.stderr
    assert tile_count(gol_path) == 1, "fixture is expected to fit into the root tile"

    actual = way_coordinates(gol_path)
    assert set(actual) == set(WAYS)
    for way_id, (nodes, _tags) in WAYS.items():
        expected = [NODES[n] for n in nodes]
        got = actual[way_id]
        assert len(got) == len(expected), f"way/{way_id} node count"
        for (lon, lat), (got_lon, got_lat) in zip(expected, got):
            assert got_lon == pytest.approx(lon, abs=1e-6), \
                f"way/{way_id} lon {got_lon} != {lon}"
            assert got_lat == pytest.approx(lat, abs=1e-6), \
                f"way/{way_id} lat {got_lat} != {lat}"

    # and the way must be findable where it really is
    res = run(["query", str(gol_path), "w", "-b", "99,9,101,11", "-f", "count"])
    assert res.returncode == 0, res.stderr
    assert int(res.stdout.strip()) == 1
