"""
Regression test for #41: `gol query -f pbf` dropped the sign bit of the
latitude of anonymous way-nodes (every untagged node south of the equator
came out shifted by +214.7483648 degrees) when the source GOL had been
built with --waynode-ids.

The fixture (test/data/hemispheres.osm.pbf, generated by
test/data/make_hemispheres.py) holds four small ways with anonymous nodes
in the northern and southern hemispheres, east and west of the prime
meridian. The test round-trips it:

    gol build -w  ->  gol query "*" -f pbf  ->  gol build

and checks that the way geometries of both GOLs match the coordinates the
fixture was generated from.

Point GOL_EXE at the binary under test, e.g.
    GOL_EXE=build/gol python3 -m pytest test/test_pbf_export.py
"""
import json
import sys
from pathlib import Path

import pytest

from conftest import run

DATA_DIR = Path(__file__).parent / "data"
FIXTURE = DATA_DIR / "hemispheres.osm.pbf"

sys.path.insert(0, str(DATA_DIR))
from make_hemispheres import NODES, WAYS  # noqa: E402  (single source of truth)


def expected_coordinates():
    """way id -> [(lon, lat), ...] as written into the fixture."""
    return {
        way_id: [(NODES[n][0], NODES[n][1]) for n in nodes]
        for way_id, (nodes, _tags) in WAYS.items()
    }


def way_coordinates(gol_path):
    """way id -> [(lon, lat), ...] as reported by `gol query * -f geojson`.

    Queries "*" (not "w") because closed ways with area tags are areas.
    """
    res = run(["query", str(gol_path), "*", "-f", "geojson"])
    assert res.returncode == 0, res.stderr
    features = json.loads(res.stdout)["features"]
    coords = {}
    for feature in features:
        if not feature["id"].startswith("W"):
            continue    # the fixture's single tagged node
        way_id = int(feature["id"][1:])
        geometry = feature["geometry"]
        if geometry["type"] == "LineString":
            ring = geometry["coordinates"]
        elif geometry["type"] == "Polygon":
            ring = geometry["coordinates"][0]
        else:
            pytest.fail(f"unexpected geometry {geometry['type']} for way/{way_id}")
        coords[way_id] = [(lon, lat) for lon, lat in ring]
    return coords


def assert_matches_fixture(gol_path, label):
    actual = way_coordinates(gol_path)
    expected = expected_coordinates()
    assert set(actual) == set(expected), f"{label}: way set differs"
    for way_id, points in expected.items():
        got = actual[way_id]
        assert len(got) == len(points), f"{label}: way/{way_id} node count"
        for (lon, lat), (got_lon, got_lat) in zip(points, got):
            assert got_lon == pytest.approx(lon, abs=1e-6), \
                f"{label}: way/{way_id} lon {got_lon} != {lon}"
            assert got_lat == pytest.approx(lat, abs=1e-6), \
                f"{label}: way/{way_id} lat {got_lat} != {lat}"


def test_pbf_export_preserves_anonymous_node_latitudes(tmp_path):
    source_gol = tmp_path / "source.gol"
    exported_pbf = tmp_path / "exported.osm.pbf"
    reimported_gol = tmp_path / "reimported.gol"

    # The bug only affects GOLs that store way-node IDs (-w): without them,
    # the exporter writes LocationsOnWays and never packs coordinates.
    res = run(["build", "-w", str(source_gol), str(FIXTURE), "-Y"])
    assert res.returncode == 0, res.stderr
    assert_matches_fixture(source_gol, "source GOL")

    res = run(["query", str(source_gol), "*", "-f", "pbf", "-o", str(exported_pbf)])
    assert res.returncode == 0, res.stderr
    assert exported_pbf.stat().st_size > 0

    res = run(["build", str(reimported_gol), str(exported_pbf), "-Y"])
    assert res.returncode == 0, res.stderr
    assert_matches_fixture(reimported_gol, "GOL rebuilt from exported PBF")
