// Copyright (c) 2026 Clarisma / GeoDesk contributors
// SPDX-License-Identifier: LGPL-3.0-only

#pragma once
#include <cstdint>
#ifndef NOMINMAX
// Prevent Windows headers from clobbering min/max
#define NOMINMAX
#include <windows.h>
#endif
#include <winhttp.h>

namespace clarisma {

/// HTTP operation errors (WinHTTP backend).
enum class HttpError : uint32_t
{
    SUCCESS = ERROR_SUCCESS,
    UNKNOWN = 0x10000,

    // Connection
    CONNECTION = ERROR_WINHTTP_CANNOT_CONNECT,
    NAME_RESOLUTION = ERROR_WINHTTP_NAME_NOT_RESOLVED,
    CONNECTION_LOST = ERROR_WINHTTP_CONNECTION_ERROR,
    CONNECTION_TIMEOUT = ERROR_WINHTTP_TIMEOUT,
    TIMEOUT = ERROR_WINHTTP_TIMEOUT,
    CANCELED = ERROR_WINHTTP_OPERATION_CANCELLED,

    // Data transfer
    READ = CONNECTION_LOST,
    WRITE = CONNECTION_LOST,
    PAYLOAD_TOO_LARGE = ERROR_WINHTTP_RESPONSE_DRAIN_OVERFLOW,
    RESOURCE_EXHAUSTION = ERROR_NOT_ENOUGH_MEMORY,

    // HTTP protocol
    HTTP_PARSING = ERROR_WINHTTP_INVALID_SERVER_RESPONSE,
    INVALID_HEADERS = ERROR_WINHTTP_INVALID_HEADER,
    INVALID_REQUEST_LINE = HTTP_PARSING,
    INVALID_HTTP_METHOD = HTTP_PARSING,
    INVALID_HTTP_VERSION = HTTP_PARSING,
    INVALID_RANGE_HEADER = HTTP_PARSING,

    TOO_MANY_REDIRECTS = ERROR_WINHTTP_REDIRECT_FAILED,
    REDIRECT_FAILED = TOO_MANY_REDIRECTS,
    RESEND_REQUEST = ERROR_WINHTTP_RESEND_REQUEST,

    INVALID_URL = ERROR_WINHTTP_INVALID_URL,
    UNSUPPORTED_SCHEME = ERROR_WINHTTP_UNRECOGNIZED_SCHEME,
    URI_TOO_LONG = 0x10001,

    HEADER_NOT_FOUND = ERROR_WINHTTP_HEADER_NOT_FOUND,
    HEADER_COUNT_EXCEEDED =
        ERROR_WINHTTP_HEADER_COUNT_EXCEEDED,
    HEADER_SIZE_EXCEEDED =
        ERROR_WINHTTP_HEADER_SIZE_OVERFLOW,
    CHUNKED_ENCODING_OVERFLOW =
        ERROR_WINHTTP_CHUNKED_ENCODING_HEADER_SIZE_OVERFLOW,

    // TLS
    SSL_CONNECTION = ERROR_WINHTTP_SECURE_CHANNEL_ERROR,
    SSL_SERVER_VERIFICATION = ERROR_WINHTTP_SECURE_FAILURE,
    SSL_HOSTNAME_VERIFICATION =
        ERROR_WINHTTP_SECURE_CERT_CN_INVALID,
    SSL_CERT_DATE_INVALID =
        ERROR_WINHTTP_SECURE_CERT_DATE_INVALID,
    SSL_CERT_INVALID_CA = ERROR_WINHTTP_SECURE_INVALID_CA,
    SSL_CERT_INVALID = ERROR_WINHTTP_SECURE_INVALID_CERT,
    SSL_CERT_REVOKED = ERROR_WINHTTP_SECURE_CERT_REVOKED,
    SSL_CERT_REVOCATION_FAILED =
        ERROR_WINHTTP_SECURE_CERT_REV_FAILED,
    SSL_CERT_WRONG_USAGE =
        ERROR_WINHTTP_SECURE_CERT_WRONG_USAGE,
    SSL_CLIENT_CERT_REQUIRED =
        ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED,
    SSL_CLIENT_CERT_NO_PRIVATE_KEY =
        ERROR_WINHTTP_CLIENT_CERT_NO_PRIVATE_KEY,
    SSL_CLIENT_CERT_PRIVATE_KEY_ACCESS =
        ERROR_WINHTTP_CLIENT_CERT_NO_ACCESS_PRIVATE_KEY,

    // Proxy
    PROXY_CONNECTION = CONNECTION,
    PROXY_AUTO_CONFIG_ERROR =
        ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR,
    PROXY_AUTODETECTION_FAILED =
        ERROR_WINHTTP_AUTODETECTION_FAILED,
    PROXY_SCRIPT_ERROR = ERROR_WINHTTP_BAD_AUTO_PROXY_SCRIPT,
    PROXY_SCRIPT_DOWNLOAD =
        ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT,
    PROXY_SCRIPT_UNSUPPORTED =
        ERROR_WINHTTP_UNHANDLED_SCRIPT_TYPE,
    PROXY_SCRIPT_EXECUTION =
        ERROR_WINHTTP_SCRIPT_EXECUTION_ERROR,

    // Authentication
    LOGIN_FAILURE = ERROR_WINHTTP_LOGIN_FAILURE,

    // State and configuration
    INTERNAL_ERROR = ERROR_WINHTTP_INTERNAL_ERROR,
    INVALID_OPTION = ERROR_WINHTTP_INVALID_OPTION,
    OPTION_NOT_SETTABLE = ERROR_WINHTTP_OPTION_NOT_SETTABLE,
    INVALID_HANDLE_TYPE =
        ERROR_WINHTTP_INCORRECT_HANDLE_TYPE,
    INVALID_HANDLE_STATE =
        ERROR_WINHTTP_INCORRECT_HANDLE_STATE,
    CANNOT_CALL_BEFORE_OPEN =
        ERROR_WINHTTP_CANNOT_CALL_BEFORE_OPEN,
    CANNOT_CALL_BEFORE_SEND =
        ERROR_WINHTTP_CANNOT_CALL_BEFORE_SEND,
    CANNOT_CALL_AFTER_SEND =
        ERROR_WINHTTP_CANNOT_CALL_AFTER_SEND,
    CANNOT_CALL_AFTER_OPEN =
        ERROR_WINHTTP_CANNOT_CALL_AFTER_OPEN,
    SHUTDOWN = ERROR_WINHTTP_SHUTDOWN,

    // cpp-httplib-only errors without a reliable WinHTTP equivalent
    BIND_IP_ADDRESS = 0x10002,
    SSL_LOADING_CERTS = 0x10003,
    UNSUPPORTED_MULTIPART_BOUNDARY = 0x10004,
    COMPRESSION = 0x10005,
    TOO_MANY_FORM_FILES = 0x10006,
    TOO_MANY_SOCKETS = 0x10007,
    MULTIPART_PARSING = 0x10008,
    OPEN_FILE = 0x10009,
    LISTEN = 0x1000A,
    GET_SOCKET_NAME = 0x1000B,
    UNSUPPORTED_ADDRESS_FAMILY = 0x1000C,
    UNSUPPORTED_CONTENT_ENCODING = 0x1000D,
    WEBSOCKET_HANDSHAKE = 0x1000E,
    USER_CALLBACK_EXCEPTION = 0x1000F,
};

} // namespace clarisma